const fetch = require('node-fetch');
const User = require('../models/User');
const ActionItem = require('../models/ActionItem');
const EventCache = require('../models/EventCache');
const SummaryDigest = require('../models/SummaryDigest');
const { getFreshAccessTokenForUser } = require('../utils/graphTokenStore');

function istParts(d = new Date()) { return new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Kolkata', weekday: 'short', hour: '2-digit', minute: '2-digit', hour12: false, year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(d).reduce((a,p)=>(a[p.type]=p.value,a),{}); }
function startOfDay(d){ const x=new Date(d); x.setHours(0,0,0,0); return x; }
function endOfDay(d){ const x=new Date(d); x.setHours(23,59,59,999); return x; }
function addDays(d,n){ const x=new Date(d); x.setDate(x.getDate()+n); return x; }
async function sendMail(accessToken,{to,subject,body}){ const r=await fetch('https://graph.microsoft.com/v1.0/me/sendMail',{method:'POST',headers:{Authorization:`Bearer ${accessToken}`,'Content-Type':'application/json'},body:JSON.stringify({message:{subject,body:{contentType:'Text',content:body},toRecipients:[{emailAddress:{address:to}}]},saveToSentItems:true})}); if(!r.ok) throw new Error(await r.text()); }
async function buildDigestForUser(user,type){ const now=new Date(); const start= type==='weekly'? startOfDay(addDays(now,-6)) : startOfDay(now); const end=endOfDay(now); const email=String(user.email||'').toLowerCase(); const open=await ActionItem.find({orgId:user.org, 'acl.allowedEmails': email, status:{$in:['Open','In Progress']}}).sort({dueDateISO:1,createdAt:-1}).limit(25).lean(); const done=await ActionItem.find({orgId:user.org, 'acl.allowedEmails': email, status:'Done', updatedAt:{$gte:start,$lte:end}}).sort({updatedAt:-1}).limit(25).lean(); const meetings=await EventCache.find({orgId:user.org, userEmail:email, startDateTime:{$gte:start.toISOString(),$lte:end.toISOString()}}).sort({startDateTime:1}).limit(30).lean(); const subject=`${type==='weekly'?'Weekly':'Daily'} CEO summary - ${new Date().toLocaleDateString('en-IN')}`; const body=[` ${subject}`,'',`Focus items:`,...(open.length?open.map((a,i)=>`${i+1}. ${a.title} — ${a.ownerName||'Unassigned'} — ${a.dueDate||'Unclear'} — ${a.status}`):['No open focus items found.']),'',`Completed:`,...(done.length?done.map((a,i)=>`${i+1}. ${a.title} — ${a.ownerName||'Unassigned'}`):['No completed items recorded in the period.']),'',`Meetings:`,...(meetings.length?meetings.map((m,i)=>`${i+1}. ${m.subject||'Meeting'} — ${m.startDateTime||''}`):['No cached meetings found.'])].join('\n'); return {start,end,subject,body}; }
async function runDueSummaryDigests(){ const p=istParts(); if (!(p.hour==='07' && p.minute==='00')) return; const type = p.weekday === 'Sun' ? 'weekly' : (['Mon','Tue','Wed','Thu','Fri'].includes(p.weekday) ? 'daily' : null); if(!type) return; const users=await User.find({status:'active', role:{$in:['ceo','super_admin']}}).select({email:1,name:1,org:1}).lean(); for(const u of users){ try{ const d=await buildDigestForUser(u,type); const digest=await SummaryDigest.findOneAndUpdate({orgId:u.org,userId:u._id,type,periodStart:d.start},{$setOnInsert:{orgId:u.org,userId:u._id,email:u.email,type,periodStart:d.start,periodEnd:d.end,subject:d.subject,body:d.body,status:'created'}},{upsert:true,new:true}); if(digest.sentAt) continue; const token=await getFreshAccessTokenForUser(u._id); await sendMail(token,{to:u.email,subject:d.subject,body:d.body}); digest.sentAt=new Date(); digest.status='sent'; await digest.save(); }catch(e){ console.warn('[summary-digest]', u.email, e.message||e); } } }
function startSummaryDigestScheduler(){ if(String(process.env.DISABLE_SUMMARY_DIGESTS||'').toLowerCase()==='true') return; setInterval(()=>runDueSummaryDigests().catch(e=>console.warn('[summary-digest]',e.message||e)),60*1000); console.log('Summary digest scheduler enabled: weekdays 7 AM IST, Sunday weekly summary.'); }
module.exports={startSummaryDigestScheduler, runDueSummaryDigests};
